apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-deployment
  namespace: 'default'
  labels:
    app: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
        - name: chatapp
          image: gnodhn/chatapp
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: '100m'
              memory: '100Mi'
            limits:
              cpu: '200m'
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-svc
  namespace: 'default'
spec:
  type: NodePort
  selector:
    app: chatapp
  clusterIP: 172.20.80.81
  ports:
    - name: tcp8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30180
